"""add new table 'messages'

Revision ID: d8b95e67f39a
Revises: 206f71e2c6ee
Create Date: 2025-09-18 14:49:35.169005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8b95e67f39a"
down_revision: Union[str, Sequence[str], None] = "206f71e2c6ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("modified", "unmodified", "deleted", name="statusmessage"),
            server_default="unmodified",
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # statustask_enum = sa.Enum(
    #     "in_progress", "done", "failed",
    #     name="statustask"
    # )
    # statustask_enum.create(op.get_bind())

    # op.alter_column(
    #     "tasks",
    #     "status",
    #     existing_type=postgresql.ENUM(
    #         "in_progress", "done", "failed", name="status"
    #     ),
    #     type_=statustask_enum,
    #     existing_nullable=False,
    #     server_default="in_progress",
    #     # existing_server_default=sa.text("'in_progress'::status"),
    #     postgresql_using="status::text::statustask",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "tasks",
    #     "status",
    #     existing_type=sa.Enum(
    #         "in_progress", "done", "failed", name="statustask"
    #     ),
    #     type_=postgresql.ENUM("in_progress", "done", "failed", name="status"),
    #     existing_nullable=False,
    #     existing_server_default=sa.text("'in_progress'::status"),
    # )
    op.drop_table("messages")
    # ### end Alembic commands ###
