"""add new role for user

Revision ID: 206f71e2c6ee
Revises: db3c1f7f5184
Create Date: 2025-09-12 13:58:08.992795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "206f71e2c6ee"
down_revision: Union[str, Sequence[str], None] = "db3c1f7f5184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text("ALTER TYPE role ADD VALUE IF NOT EXISTS 'guest';"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
