"""add role to users

Revision ID: db3c1f7f5184
Revises: 36ae1dd4417d
Create Date: 2025-09-09 20:39:26.283649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db3c1f7f5184"
down_revision: Union[str, Sequence[str], None] = "36ae1dd4417d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create type role as enum ('user', 'admin');")
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="role"),
            server_default="user",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
