"""add new field 'text'

Revision ID: 6ffc19c3abef
Revises: d8b95e67f39a
Create Date: 2025-09-18 14:56:23.388205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ffc19c3abef"
down_revision: Union[str, Sequence[str], None] = "d8b95e67f39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("text", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "text")
    # ### end Alembic commands ###
